import { MouseEventHandler, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "../components/RandomFox";
import { random } from "lodash";

const myRandom = () => random(1, 123);

//generate simple unique id
const generateId = () => Math.random().toString(36).slice(2, 9);


const Home: NextPage = () => {
  const[images, setImages] = useState<Array<IFoxImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) =>{
    const newImageItem: IFoxImageItem={
        id: generateId(), 
        url:`https://randomfox.ca/images/${myRandom()}.jpg`
    };
    setImages([
      ...images,
      newImageItem
    ]);
    window.plausible("add_fox");
  }
  return (
    <div>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
         defer
        data-domain="yourdomain.com"
        src="https://plausible.io/js/script.js"
        ></script>
       
      </Head>

      <main className="p-8 bg-gray-100 min-h-screen">
  <h1 className="text-4xl font-extrabold text-center text-indigo-600 mb-6">
    Hey Platzi 😎!
  </h1>
  <button
    onClick={addNewFox}
    className="bg-blue-500 text-white px-6 py-2 rounded-lg shadow-md hover:bg-blue-600 transition-colors duration-300 mb-6 block mx-auto"
  >
    Add new fox
  </button>
  <div className="flex flex-wrap justify-center gap-6">
    {images.map(({ id, url }) => (
      <div key={id} className="p-4 bg-white shadow-lg rounded-lg w-80 h-80 flex justify-center items-center hover:scale-105 transition-transform duration-300">
        <LazyImage
          src={url}
          width={320}
          height={320}
          className="rounded-lg bg-gray-300 w-full h-full object-cover"
          title="Random Fox"
          onClick={() => console.log('hey')}
        />
      </div>
    ))}
  </div>
</main>


      <footer></footer>
    </div>
  );
};

export default Home;